Fix windows.h conflict with Criterion::STRICT
If window.h is included in the same compilation unit we can expect this kind of errors:
```
util.hpp:348:15: error: expected identifier before ‘,’ token
  348 |         STRICT,
```