PROJ: add missing <cstdint> includes
Without the change build fails on upcomig `gcc-13` as:

    In file included from /build/PROJ/src/iso19111/operation/conversion.cpp:58:
    src/proj_json_streaming_writer.hpp:42:14:
      error: 'int64_t' in namespace 'std' does not name a type
       42 | typedef std::int64_t GIntBig;
          |              ^~~~~~~

gcc-13 cleaned it's header dependencies and that exposes these failures.